# Generated by Django 5.2.15 on 2026-07-04 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyvideo',
            name='video',
        ),
    ]
