# Generated by Django 6.0.7 on 2026-07-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('booking_fee', 'Booking Fee'), ('inspection_fee', 'Inspection Fee'), ('deposit', 'Deposit'), ('full_payment', 'Full Payment'), ('agency_fee', 'Agency Fee'), ('verification_fee', 'Agent Verification Fee')], max_length=20),
        ),
    ]
